### ISSUE TITLE
Should `pig me` include pulls that I opened but someone else is assigned?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/PBot#70]
Eg: https://github.com/Particular/NServiceBus/pull/3337

I'd say no since, @MarcinHoppe , in this case is dealing with it?

**Comment by adamralph** [comment]
I say yes :wink:

You're a pig in that PR, not a chicken.

**Comment by andreasohlund** [comment]
Fair enough, how about we add something to the output to show that? 

`... (Assigned to: {user})`

**Comment by adamralph** [comment]
Conclusion for now seems to be that pbot pig should continue to include PRs which the user opened, since they are a pig in that PR.

We could add more refined commands for picking out only issue where the user is in the task force, but given that GitHub now supports multiple assignees, pbot pig is probably going to be retired in the not too distant future.
