### ISSUE TITLE
pbot pinging users with issues not related to them

### ISSUE THREAD

**Issue by johnsimons** [Particular/PBot#9]
Steps:

1. run `pbot remind users of mandatory bug sections`
2. Find

    ```
    Hi there @john! I've seen that this bug is missing some mandatory sections. Please head over to     https://github.com/Particular/ServiceInsight/issues/414 and update it! Read more on required sections  here: https://github.com/Particular/Housekeeping/wiki/Required-sections-for-bugs
    ``` 
3. Open https://github.com/Particular/ServiceInsight/issues/414, this issue has no mention of johnsimons!

**Comment by andreasohlund** [comment]
Yes, I've seen this as well. There is a todo that needs a octokit patch to be fixed

https://github.com/Particular/PBot/blob/master/src/PBot/Reminders/RemindUsersOfBugsWithMissingSections.cs#L64

that said I can't understand how this could include you john:

https://github.com/Particular/PBot/blob/master/src/PBot/Reminders/RemindUsersOfBugsWithMissingSections.cs#L65

@distantcam @SimonCropp since you guys are familiar with octokit can you spot anything wrong?

**Comment by andreasohlund** [comment]
Vierd, ran it locally and got:

```
Hi @channel! The github user indualagarsamy closed this issue and I can't seem to find what slack username that maps to. Would you please remind the user that this bug is missing some mandatory sections. Please head over to https://github.com/Particular/ServiceInsight/issues/414
```

which seems to be correct?
